name: Review eslint
on:
  pull_request:
    types: [opened, reopened]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: eslintによるレビュー
        uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: ". --ext .js,.ts,.vue"
          fail_on_error: true
          level: info
          reporter: github-pr-review
